*Ctrl+Shift+Enter* - run code
*Ctrl+Alt+I* - insert new chunk
*install.packages("PackageName")* - install library


```{r}
# load the packages
library(RWeka)
library(caTools)
library(dplyr)
library("Rgraphviz")
library(partykit)
library(caret)
library(ROCR)
library(rBayesianOptimization)

```

Load IRIS dataset
```{r}
# set.seed(17)  # set a seed to get replicable results

iris <- read.csv(file="datasets/iris.csv", head=FALSE, sep=";", fileEncoding="UTF-8-BOM")
# iris <- iris[sample(1:nrow(iris)), ]  # shuffle

head(iris)
# plot(iris)  # show dataset
```

Write first for loop in R :D
```{r}
folds <- c(2,3,5,10)
for (k in folds){
  cat("k =", k, "\n")
}
```
```{r}
k_params <- list()
folds <- c(2,3,5,10)

for (i in seq(length(folds))){
  k_params[i] <- folds[i]
}

```


Trying training model with cross validation
```{r}
# split

folds_indices <- createFolds(iris$V5, k=10)
model <- train(V5 ~ V1+V2+V3+V4, method="J48", data=iris, 
               trControl = trainControl(method="cv", indexOut=folds_indices))
```

```{r}
model$finalModel$tuneValue
model$finalModel
```



Train single model
```{r}
model <- J48(V5 ~ V1+V2+V3+V4, data=iris) 
model

folds_indices <- createFolds(iris$V5, k=5) 
# folds_indices

tc <- trainControl(method="cv", indexOut=folds_indices)
# tc

model <- train(V5 ~ V1+V2+V3+V4, method="J48", data=iris, tuneLength = 7, trControl = tc)
```


Try to train several models - with different cross validation parameter
```{r}

folds <- c(2,3,5,10)
models <- vector("list", length(folds))

for (k_param in folds){
  cat("Training for k =", k_param, "\n")
  folds_indices <- createFolds(iris$V5, k=5)
  model <- train(V5 ~ V1+V2+V3+V4, method="J48", data=iris, tuneLength = 7, 
                 trControl = trainControl(method="cv", indexOut=folds_indices))
  
  # models[[i]] <- model
}
cat("\nAll models has been trained :)")

```

```{r}
summary(iris)
iris

```



```{r}

k <- 5
folds_indices <- createFolds(iris$V5, k=k)
f <- folds_indices[i]

iris[c(f),]


# for (i in length(folds_indices)) {
#   test_ind <- folds_indices[i]
#   test <- list()
#   for (ind in length(test_ind)) {
#     test[ind] <- iris[test_ind,]
#   }
# 
# 
# }
```
```{r}

k <- 5
# f_ind <- createFolds(iris$V5, k=k)
# 
# f_ind[[2]]
# f_ind[2]
# f_ind$Fold2
# 
# 
# attributes(f_ind)
# 
# test <- iris[f_ind[[2]], ]
# train <- iris[f_ind[[2]], ]
# 
# 
# flds <- createFolds(iris$V5, k = 10, list = TRUE, returnTrain = FALSE)
# names(flds)[1] <- "train"
# names(flds)


# # Create 10 equally size folds
# folds <- cut(seq(1,nrow(iris)),breaks=3,labels=FALSE)
# folds_indices <- createFolds(iris$V5, k=k)
# 
# # Perform 10 fold cross validation
# for(i in 1:5){
#     #Segement your data by fold using the which() function 
#     testIndexes <- which(folds_indices==i,arr.ind=TRUE)
#     testData <- iris[testIndexes, ]
#     trainData <- iris[-testIndexes, ]
#     #Use the test and train data partitions however you desire...
#     testData
#     trainData
#     print(testData, row.names = FALSE)
#     summary(testData)
# }



```


```{r}
folds <- KFold(iris$V5, nfolds = 10, stratified = TRUE, seed = 0)
# folds

str(folds[[1]])
iris[folds[[1]],]

iris[-folds[[1]],]



```



